# Generated by Django 3.1.5 on 2021-08-31 07:10

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='record',
            field=models.FileField(upload_to=chat.models.MessageRecordStorage),
        ),
    ]
