# Generated by Django 3.1.5 on 2021-09-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210901_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content_or_record',
            new_name='record',
        ),
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
