# Generated by Django 3.1.5 on 2021-09-16 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20210901_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonymousmessagemedia',
            name='message',
        ),
        migrations.AddField(
            model_name='message',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m_replies', to='chat.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anonymous_messages', to='chat.anonymousroom'),
        ),
        migrations.DeleteModel(
            name='AnonymousMessage',
        ),
        migrations.DeleteModel(
            name='AnonymousMessageMedia',
        ),
    ]
