# Generated by Django 3.1.5 on 2021-09-16 14:19

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20210916_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='record',
            field=models.FileField(blank=True, null=True, upload_to=chat.models.MessageRecordStorage),
        ),
    ]
