# Generated by Django 3.1.5 on 2021-09-06 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0002_auto_20210906_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='record',
        ),
    ]
