# Generated by Django 3.1.5 on 2021-09-07 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0003_remove_post_record'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='video',
            new_name='media',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='img',
        ),
    ]
