# Generated by Django 3.1.5 on 2021-09-12 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0004_auto_20210907_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_reply',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_snippet',
        ),
    ]
