# Generated by Django 3.1.5 on 2021-09-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0006_auto_20210921_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postfiles',
            name='caption',
        ),
        migrations.AddField(
            model_name='postfiles',
            name='content',
            field=models.TextField(default='sb7'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
    ]
