# Generated by Django 3.1.5 on 2021-09-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_auto_20210830_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
