# Generated by Django 3.1.5 on 2021-09-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_auto_20210905_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_anonymous',
            field=models.BooleanField(default=True),
        ),
    ]
