# Generated by Django 3.1.5 on 2021-09-06 17:20

from django.db import migrations, models
import media.models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_user_allow_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover',
            field=models.ImageField(blank=True, default='profiles/cover.webp', null=True, upload_to=media.models.get_profile_cover_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.ImageField(blank=True, default='profiles/profile.jpg', null=True, upload_to=media.models.get_profile_pic_path),
        ),
    ]
