# Generated by Django 3.1.5 on 2021-09-06 17:21

from django.db import migrations, models
import media.models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_auto_20210906_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover',
            field=models.ImageField(blank=True, default='profiles/cover.jpg', null=True, upload_to=media.models.get_profile_cover_path),
        ),
    ]
