# Generated by Django 3.1.5 on 2021-09-07 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0009_auto_20210907_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
    ]
