# Generated by Django 3.1.5 on 2021-09-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0010_auto_20210907_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], null=True),
        ),
    ]
