# Generated by Django 3.1.5 on 2021-09-16 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0011_auto_20210907_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pic',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='cover',
            new_name='cover_pic',
        ),
    ]
