# Generated by Django 3.1.5 on 2021-09-16 08:24

from django.db import migrations, models
import media.models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0012_auto_20210916_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=media.models.get_profile_pic_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover_pic',
            field=models.ImageField(blank=True, null=True, upload_to=media.models.get_profile_cover_path),
        ),
    ]
